services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    depends_on:
      - users-service
      - payments-service
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=dev-secret-please-change
    ports:
      - "8080:8080"

  users-service:
    build: ./users-service
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  payments-service:
    build: ./payments-service
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082:8082"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - gateway

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
